### ISSUE TITLE
Test failures with with Test-Simple-1.302014_001

### ISSUE THREAD

**Issue by eserte** [Test-More/test-exception#14]
While testing NHORNE/CGI-Info-0.59.tar.gz with the latest Test-Simple in PERL5LIB I got the following errors:

```
Undefined subroutine &Test2::Global::test2_stack called at /opt/perl-5.22.0/lib/site_perl/5.22.0/Test/Exception.pm line 351.
Compilation failed in require at (eval 42) line 2.
BEGIN failed--compilation aborted at (eval 42) line 2.
 at t/00-load.t line 5.
BEGIN failed--compilation aborted at t/00-load.t line 5.
t/00-load.t .... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
... (similar fails follow) ...
```

**Comment by exodist** [comment]
What version of Test::Exception are you using? I suspect you need to update Test::Exception. Also, did the very end of the test tell you as much about Test::Exception?

**Comment by eserte** [comment]
For the record: 0.41 was installed. Smoker is upgraded to use 0.43.
