### ISSUE TITLE
Test fails with alpha of Test::More latest.

### ISSUE THREAD

**Issue by magnolia-k** [Test-More/test-exception#4]
Rather than the number of rows in the test script, the number of rows of Test::Execption is displayed.

	$ ./Build test
	t/Exception.t ... ok     
	t/caller.t ...... ok   
	t/edge-cases.t .. skipped: stuff relating to RT#24678 that I have not fixed yet
	t/import.t ...... ok   
	t/isa.t ......... ok   
	t/lives_and.t ... 1/3 
	#   Failed test 'lives_and works'
	#   at t/lives_and.t line 31.
	# STDERR is:
	# #   Failed test 'lives_and, no_exception & failure'
	# #   at /xxxxxxxxxxxxxxxx/dev/test-exception/blib/lib/Test/Exception.pm line 346.
	# #          got: '42'
	# #     expected: '24'
	# #   Failed test 'lives_and, exception'
	# #   at t/lives_and.t line 26.
	# # died: oops at t/lives_and.t line 11.
	# 
	# not:
	# /#\s+Failed\ test.*?\n?.*?at\ t\/lives_and\.t line 21.*\n?/
	# #          got: '42'
	# #     expected: '24'
	# /#\s+Failed\ test.*?\n?.*?at\ t\/lives_and\.t line 26.*\n?/
	# # died: oops at t/lives_and.t line 11.
	# 
	# as expected
	t/lives_and.t ... Failed 1/3 subtests 
	t/preserve.t .... ok   
	t/return.t ...... ok     
	t/rt.t .......... ok   
	t/stacktrace.t .. ok   
	t/throws_ok.t ... ok   

	Test Summary Report
	-------------------
	t/lives_and.t (Wstat: 0 Tests: 3 Failed: 1)
	  Failed test:  3
	Files=11, Tests=53,  1 wallclock secs ( 0.07 usr  0.03 sys +  1.02 cusr  0.13 csys =  1.25 CPU)
	Result: FAIL
	Failed 1/11 test programs. 1/53 subtests failed.

	$ perl -e 'use Test::More 999999'
	Test::More version 999999 required--this is only version 1.301001039 at -e line 1.
	BEGIN failed--compilation aborted at -e line 1.

The issue did not occur in Test::More 0.98.

**Comment by exodist** [comment]
No longer an issue.
